### PR TITLE
Added support for .git directory

### PR DESCRIPTION
**Pull request by lzap**
I keep my tag files in .git/ directory which is handy approach - you never need
to push changes into .gitignore for project which don't have it yet.

### CODE REVIEW

**Comment by aki77** [comment]
Thanks!

**Comment by lzap** [comment]
Wow, update is out. Thanks!

**Comment by lzap** [comment]
Hmm getting

```
Uncaught (in promise) TypeError: Cannot read property 'apply' of undefined(…)  in ctags-provider.coffee:65
```

with Atom stable 1.6.2. This is perhaps unrelated to this patch, I can also see it with tags file in project root dir.

**Comment by aki77** [comment]
I can't reproduce the error. (Atom 1.6.2 & osx)
Can you post stack trace?

**Pull request merged**
